x-ask-automatic-config: &askAutomaticConfig
  method: POST
  headers:
    Content-Type: application/json
    Authorization: "Bearer {{env.AUTH0_TOKEN}}"
  body: "{{request_body | dump}}"
  responsePath: answer

providers:
  - id: "{{env.READER_API_URL}}/ask-automatic?prompt_version=v0"
    label: ask-automatic-v0
    config: *askAutomaticConfig
  - id: "{{env.READER_API_URL}}/ask-automatic?prompt_version=v1"
    label: ask-automatic-v1
    config: *askAutomaticConfig
  - id: "{{env.READER_API_URL}}/ask-automatic?prompt_version=v2"
    label: ask-automatic-v2
    config: *askAutomaticConfig

tests: file://test-cases/historical-allusion/*.yaml

defaultTest:
  assert:
    - type: llm-rubric
      provider: google:{{env.GEMINI_MODEL}}
      threshold: 12
      rubricPrompt: file://rubric-prompt.yaml
      value: file://rubric.txt
    - type: factuality
      provider: google:{{env.GEMINI_MODEL}}
      value: "{{reference_answer}}"
  options:
    # https://www.promptfoo.dev/docs/configuration/expected-outputs/model-graded/factuality/
    factuality:
      subset: 0
      superset: 1
      agree: 1
      disagree: 0
      differButFactual: 1
  vars:
    prompt: "{{request_body | dump}}"
