/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current User */
        get: operations["get_current_user_api_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reading-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upsert Reading State */
        post: operations["upsert_reading_state_api_reading_state_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reading-locations/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Latest Reading Location */
        get: operations["get_latest_reading_location_api_reading_locations_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ask-freeform": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Freeform */
        post: operations["ask_freeform_api_ask_freeform_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ask-automatic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Automatic */
        post: operations["ask_automatic_api_ask_automatic_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AskRequestModel */
        AskRequestModel: {
            /** Question */
            question: string;
            locator: components["schemas"]["LocatorModel"];
            /** Publication Id */
            publication_id: string;
        };
        /** AskResponseModel */
        AskResponseModel: {
            /** Answer */
            answer: string;
        };
        /** AutomaticAnswersRequestModel */
        AutomaticAnswersRequestModel: {
            /**
             * Publication Id
             * @description Publication identifier for the book being read.
             */
            publication_id: string;
            /** @description Locator describing the user's current position. */
            locator: components["schemas"]["LocatorModel"];
            /** @description Current viewport with text and selection. */
            viewport: components["schemas"]["ViewportPayloadModel"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponseModel */
        HealthResponseModel: {
            /** Ok */
            ok: boolean;
            /** Timestamp Ms */
            timestamp_ms: number;
        };
        /**
         * LocationsModel
         * @description Locations object within a Locator
         *     https://readium.org/architecture/models/locators/
         */
        LocationsModel: {
            /**
             * Fragments
             * @description Fragments (e.g., epubcfi) pointing into the resource.
             * @example [
             *       "epubcfi(/6/4!/2)"
             *     ]
             */
            fragments?: string[] | null;
            /**
             * Position
             * @description Position within the publication spine (e.g., page number).
             * @example 12
             */
            position?: number | null;
            /**
             * Progression
             * @description Progression within the resource (0.0-1.0).
             * @example 0.42
             */
            progression?: number | null;
            /**
             * Totalprogression
             * @description Progression within the entire publication (0.0-1.0).
             * @example 0.27
             */
            totalProgression?: number | null;
        };
        /**
         * LocatorModel
         * @description Readium Web Publication Manifest Locator
         *     https://readium.org/architecture/models/locators/#the-locator-object
         */
        LocatorModel: {
            /**
             * Href
             * @description Spine item href for the current location.
             * @example /text/chapter1.xhtml
             */
            href: string;
            /**
             * Type
             * @description Media type of the resource.
             * @example application/xhtml+xml
             */
            type: string;
            /**
             * Title
             * @description Optional title for the chapter/section.
             * @example Chapter 1
             */
            title?: string | null;
            /** @description Ways to locate a position within the resource. */
            locations?: components["schemas"]["LocationsModel"] | null;
            /** @description Optional text context around the locator. */
            text?: components["schemas"]["TextModel"] | null;
        };
        /** ReadingLocationResponseModel */
        ReadingLocationResponseModel: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Publication Id
             * @description Publication identifier for this reading location.
             */
            publication_id: string;
            /** @description Locator describing the user's latest known position. */
            locator: components["schemas"]["LocatorModel"];
            /**
             * Recorded At
             * @description Timestamp when the reading location was captured.
             */
            recorded_at?: string | null;
            /**
             * Created At
             * @description Timestamp when the reading location was stored.
             */
            created_at?: string | null;
        };
        /** ReadingStateResponseModel */
        ReadingStateResponseModel: {
            /** @description Latest known reading location for the user. */
            reading_location: components["schemas"]["ReadingLocationResponseModel"];
            /** @description Viewport text and offsets associated with the location, if available. */
            viewport?: components["schemas"]["ViewportResponseModel"] | null;
        };
        /** StoreReadingStateRequestModel */
        StoreReadingStateRequestModel: {
            /**
             * Publication Id
             * @description Publication identifier associated with the reading state.
             */
            publication_id: string;
            /** @description Locator describing the user's current position. */
            locator: components["schemas"]["LocatorModel"];
            /**
             * Recorded At
             * @description Timestamp when the reading state was captured.
             */
            recorded_at?: string | null;
            /** @description Optional viewport text and positions snapshot. */
            viewport?: components["schemas"]["ViewportPayloadModel"] | null;
        };
        /**
         * TextModel
         * @description Text context object within a Locator
         *     https://readium.org/architecture/models/locators/
         */
        TextModel: {
            /**
             * Before
             * @description Text immediately preceding the locator.
             * @example He opened the door and
             */
            before?: string | null;
            /**
             * Highlight
             * @description Text highlighted at the locator.
             * @example stepped into the bright sunlight
             */
            highlight?: string | null;
            /**
             * After
             * @description Text immediately after the locator.
             * @example not knowing what he'd find next.
             */
            after?: string | null;
        };
        /** UserResponseModel */
        UserResponseModel: {
            /** Email */
            email?: string | null;
            /** Display Name */
            display_name?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ViewportPayloadModel */
        ViewportPayloadModel: {
            /**
             * Positions
             * @description Ordered character offsets in the current spine item that are visible in the viewport.
             * @example [
             *       0,
             *       120
             *     ]
             */
            positions: number[];
            /**
             * Text
             * @description Visible text snippet for the user's current viewport.
             * @example It was a bright cold day in April, and the clocks were striking thirteen.
             */
            text: string;
            /**
             * Selection Text
             * @description The text that the user currently has selected from their current viewport
             * @example thirteen
             */
            selection_text?: string | null;
        };
        /** ViewportResponseModel */
        ViewportResponseModel: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Publication Id
             * @description Publication identifier for the viewport snapshot.
             */
            publication_id: string;
            /**
             * Positions
             * @description Ordered character offsets visible in the viewport.
             * @example [
             *       0,
             *       120
             *     ]
             */
            positions: number[];
            /**
             * Text
             * @description Visible text snippet captured from the viewport.
             * @example It was a bright cold day in April, and the clocks were striking thirteen.
             */
            text: string;
            /**
             * Selection Text
             * @description The text that the user currently has selected from their current viewport
             * @example thirteen
             */
            selection_text?: string | null;
            /**
             * Recorded At
             * @description Timestamp when the viewport was captured.
             */
            recorded_at?: string | null;
            /**
             * Updated At
             * @description Timestamp when the viewport was last updated.
             */
            updated_at?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseModel"];
                };
            };
        };
    };
    get_current_user_api_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseModel"];
                };
            };
        };
    };
    upsert_reading_state_api_reading_state_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreReadingStateRequestModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingStateResponseModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_reading_location_api_reading_locations_latest_get: {
        parameters: {
            query?: {
                publication_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingLocationResponseModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_freeform_api_ask_freeform_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequestModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponseModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_automatic_api_ask_automatic_post: {
        parameters: {
            query?: {
                /** @description The prompt to use for the automatic answer. */
                prompt_version?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutomaticAnswersRequestModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponseModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
